---
- name: Ensure ara container image '{{ ara_container_image }}' is {{ ara_container_image_state }}
  containers.podman.podman_image:
    name: "{{ ara_container_image }}"
    state: "{{ ara_container_image_state }}"
    pull: "{{ ara_container_image_pull }}"
    force: "{{ ara_container_image_force_pull }}"

- name: Ensure ara container '{{ ara_container_name }}' is {{ ara_container_state }}
  containers.podman.podman_container:
    name: "{{ ara_container_name }}"
    image: "{{ ara_container_image }}"
