---
jenkins_agent_user: "jenkins-agent"
jenkins_agent_user_create_home: false
jenkins_agent_user_is_system: false
jenkins_agent_user_uid: "{{ jenkins_agent_user_info.uid }}"
jenkins_agent_user_gid: "{{ jenkins_agent_user_info.group }}"

jenkins_agent_version: "3309.v27b_9314fd1a_4-5"

jenkins_agent_state: "present"
jenkins_agent_deployment_method: "docker"

jenkins_agent_name: ~
jenkins_agent_secret: ~
jenkins_agent_server_url: ~

jenkins_agent_secret_file: "/etc/jenkins/agent/{{ jenkins_agent_name }}.secret"
jenkins_agent_passwd_shim_file: "/etc/jenkins/agent/{{ jenkins_agent_name }}-passwd"
